In [34]:
import pandas as pd
import csv
import os

first_names = []
last_names = []
DOBs = []
SSNs = []
states = []

us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

employee_data = os.path.join("Resources", "employee_data2.csv")
employee_data_df = pd.read_csv(employee_data, encoding = "ISO-8859-1")


with open(employee_data, newline="") as csvfile:
    csv_reader = csv.reader(csvfile, delimiter=",")
  
    next(csv_reader, None)
    
    for row in csv_reader:
        #Split the names
        name = row[1]
        first, last = name.split(" ")
        first_names.append(first)
        last_names.append(last)
        
        #Change the dates
        date = row[2]
        year, month, day = date.split("-")
        new_date = (str(month) + "/" + str(day) + "/" + str(year))
        DOBs.append(new_date)
        
        #Change the SSNs
        social = row[3]
        part1, part2, part3 = social.split("-")
        new_social = ("***-**-" + str(part3))
        SSNs.append(new_social)
        
        #Change the State to and Abbreviation
        new_state = us_state_abbrev[str(row[4])]
        states.append(new_state)
        
#Drop the old values
employee_data_df = employee_data_df.drop(['Name','DOB','State','SSN'], axis=1)

#Add the new values
employee_data_df['First Names'] = first_names
employee_data_df['Last Names'] = last_names
employee_data_df['DOB'] = DOBs
employee_data_df['SSN'] = SSNs
employee_data_df['States'] = states

#Write the CSV file
employee_data_df.to_csv('out.csv', sep=',',index=False)
        
#states

In [9]:
employee_data_df

     Emp ID               Name         DOB          SSN           State
0       214      Sarah Simpson   12/4/1985  282-01-8166         Florida
1        15      Samantha Lara    9/8/1993  848-80-7526        Colorado
2       411      Stacy Charles  12/20/1957  658-75-8526    Pennsylvania
3       166       Michelle Roy   7/29/1978  794-25-3944        Michigan
4        39      Joseph Rogers   3/28/1985  525-40-3515       Minnesota
5       423        Erica Hines  10/13/1975  034-90-6153        New York
6       192          Zoe Patel  12/20/1967  037-50-0817       Wisconsin
7       162     Matthew Harvey   1/20/1990  244-53-0346       Tennessee
8       131        Shawn Davis   7/21/1961  309-08-1581   West Virginia
9        20      April Baldwin    8/7/1961  068-61-2014        Missouri
10      246    Vincent Daniels    1/6/1972  319-38-2754         Montana
11      525         Ann Fields   8/22/1960  752-98-7911            Iowa
12      392    Jeffrey Pearson    5/5/1979  171-82-2578        Illinois
13      474    Heather Johnson   9/23/1989  724-30-0904         Georgia
14      478   Melissa Fletcher   3/14/1979  899-91-6881    Rhode Island
15      101   Kimberly Alvarez    9/4/1984  138-08-8680       Louisiana
16       52     Monica Jimenez    4/8/1988  835-26-1668    North Dakota
17      182     Steven Johnson   5/28/1962  026-20-7070        Nebraska
18      637         Sarah Wood   6/15/1972  235-96-6715         Florida
19      510     Jesus Petersen   3/28/1958  133-75-0770        Oklahoma
20      122     Rhonda Rosales   4/10/1963  498-27-0286         Alabama
21      294  Nicole Richardson    9/9/1981  369-83-5228       Louisiana
22      327    Jennifer Mendez   7/20/1977  736-41-1994          Oregon
23      145       Sandra Petty   1/30/1981  702-18-7629  North Carolina
24      565     Michael Hester   4/13/1987  022-21-6836    South Dakota
25      590       Joseph Brown   8/28/1982  517-03-4744   New Hampshire
26      340    Michelle Cooper   8/23/1993  056-59-2306      Washington
27      176       Barbara Wise  12/15/1991  894-82-7662         Indiana
28       63      Carol Rosales   7/20/1984  874-92-4907      New Jersey
29      121         Mark Villa   2/24/1969  700-15-2207     Mississippi
..      ...                ...         ...          ...             ...
620     124        Maria Burns  11/24/1979  714-40-9488   West Virginia
621       8        Kevin Riley    9/5/1962  460-37-5605   West Virginia
622     251        Brian Reyes   7/15/1962  747-56-0510   West Virginia
623     643   Jeffrey Robinson   6/21/1958  055-93-6490        Missouri
624     238      David Gardner    9/5/1961  358-50-8396         Florida
625     303       Tracey Downs   2/28/1974  177-86-4596      New Mexico
626     519       Cody Ramirez  10/15/1982  298-47-7950       Louisiana
627     178       Heather Gray    5/9/1981  655-20-6848          Kansas
628     458        Erika Lewis   2/15/1960  449-09-9111        Colorado
629     207     Ronald Maynard  11/22/1978  734-20-9020        Kentucky
630     598    Ashley Saunders   6/11/1991  174-14-5309         Georgia
631     352       Paul Kaufman   11/2/1978  590-30-0964            Iowa
632     645     Nathan Rosario   6/15/1964  505-75-5027        New York
633     146     Melissa Nguyen   10/6/1978  348-50-1193       Minnesota
634      51      Mitchell Gill   7/27/1989  281-99-7598        Kentucky
635     512       Michael Shaw   4/18/1977  537-54-8249          Oregon
636     467      Crystal Jones  12/20/1972  502-77-8160        Maryland
637     179   Jasmine Harrison   12/4/1957  179-98-0602   West Virginia
638      54        Chase Grant    5/4/1985  721-15-1229          Kansas
639     570         Shawn Kidd   4/10/1961  210-13-4240       Minnesota
640     527     Chris Robinson   1/24/1970  453-27-1013  South Carolina
641     288        Carla Smith    5/5/1969  340-98-6182         Alabama
642     382     Kimberly Burns   1/30/1985  857-45-5610      California
643     408      Lori Sullivan   10/5/1992  682-95-4062        New York
644     147  Jennifer Williams   2/25/1994  464-83-7025           Maine
645     198          John Lamb    3/9/1986  571-58-1494        Colorado
646     194        Joanne Lamb   6/28/1974  313-30-6922       Louisiana
647     206        David Brown  12/27/1978  893-82-4274        Delaware
648      76        Scott Leach    4/3/1985  216-79-5144        Arkansas
649     432       Andrew Tyler    4/8/1970  175-03-3511            Iowa

[650 rows x 5 columns]