In [19]:
import pandas as pd
import csv
import os

election_data = os.path.join("Resources", "election_data_1.csv")
election_data_df = pd.read_csv(election_data, encoding = "ISO-8859-1")
election_data_df_noHead = pd.read_csv(election_data, encoding = "ISO-8859-1",skiprows=1, header=None)

num_of_votes = len(election_data_df_noHead)

election_data_df

        Voter ID      County Candidate
0        1405627      Harsaw    Vestal
1        1711723  Mershville    Vestal
2        1550639  Matterdawn    Vestal
3        1042621      Harsaw    Vestal
4        1583965  Matterdawn    Vestal
5        1943299  Mershville    Vestal
6        1880982      Harsaw    Torres
7        1305689      Harsaw    Torres
8        1759114  Mershville    Vestal
9        1745020  Matterdawn      Seth
10       1562401      Harsaw    Vestal
11       1467337      Porpus    Torres
12       1091170  Matterdawn    Torres
13       1947604      Harsaw    Vestal
14       1400758  Mershville    Torres
15       1009045  Matterdawn    Vestal
16       1246891  Matterdawn    Cordin
17       1744120  Matterdawn    Vestal
18       1571939  Mershville    Vestal
19       1936895  Matterdawn    Vestal
20       1122582  Matterdawn    Torres
21       1307503  Mershville    Torres
22       1594030      Harsaw    Torres
23       1072081  Mershville    Torres
24       1368919  Mershville    Vestal
25       1954121      Harsaw    Torres
26       1427438  Matterdawn    Vestal
27       1049416      Porpus    Torres
28       1619112      Harsaw    Torres
29       1725473  Mershville    Vestal
...          ...         ...       ...
802970   1243711      Porpus    Cordin
802971   1165617      Harsaw    Vestal
802972   1536635      Porpus    Torres
802973   1952569  Mershville    Vestal
802974   1900901      Harsaw    Vestal
802975   1623227  Mershville    Torres
802976   1164899      Porpus    Torres
802977   1430310      Porpus    Torres
802978   1421648  Mershville    Vestal
802979   1966539  Matterdawn    Vestal
802980   1048447      Arrent    Vestal
802981   1220171      Arrent    Vestal
802982   1546597  Matterdawn    Torres
802983   1454316      Harsaw    Vestal
802984   1273447  Matterdawn    Vestal
802985   1642944  Matterdawn    Torres
802986   1009803      Harsaw    Torres
802987   1348943      Porpus    Vestal
802988   1984510  Mershville    Vestal
802989   1242544      Porpus    Vestal
802990   1370412      Harsaw    Torres
802991   1071339      Porpus    Vestal
802992   1232786      Porpus    Vestal
802993   1872696  Matterdawn    Torres
802994   1818021      Porpus    Vestal
802995   1165505      Harsaw    Vestal
802996   1923858      Harsaw    Torres
802997   1959786  Matterdawn    Torres
802998   1768101  Matterdawn    Torres
802999   1320393      Harsaw    Torres

[803000 rows x 3 columns]

In [14]:
candidate_array = election_data_df['Candidate'].unique()
cand1 = candidate_array[0]
cand2 = candidate_array[1]
cand3 = candidate_array[2]
cand4 = candidate_array[3]

'Seth'

In [9]:
election_data_df['Candidate'].value_counts()

Vestal    385440
Torres    353320
Seth       40150
Cordin     24090
Name: Candidate, dtype: int64

In [33]:
candidate_array = election_data_df['Candidate'].unique()
cand1 = candidate_array[0]
cand2 = candidate_array[1]
cand3 = candidate_array[2]
cand4 = candidate_array[3]

cand1_count = 0
cand2_count = 0
cand3_count = 0
cand4_count = 0


with open(election_data, newline="") as csvfile:
    csv_reader = csv.reader(csvfile, delimiter=",")
    
    for row in csv_reader:
        if row[2] == str(cand1):
            cand1_count = cand1_count + 1
        if row[2] == str(cand2):
            cand2_count = cand2_count + 1
        if row[2] == str(cand3):
            cand3_count = cand3_count + 1
        if row[2] == str(cand4):
            cand4_count = cand4_count + 1
            
            
highest_vote_count = 0
election_winner = "No one"

if cand1_count > cand2_count:
    highest_vote_count = cand1_count
    election_winner = str(cand1)
if cand2_count > cand1_count:
    highest_vote_count = cand2_count
    election_winner = str(cand2)
if cand3_count > highest_vote_count:
    highest_vote_count = cand3_count
    election_winner = str(cand3)
if cand4_count > highest_vote_count:
    highest_vote_count = cand4_count
    election_winner = str(cand4)
               
            
prop_of_cand1_votes = (cand1_count / num_of_votes)           
prop_of_cand2_votes = (cand2_count / num_of_votes)
prop_of_cand3_votes = (cand3_count / num_of_votes)
prop_of_cand4_votes = (cand4_count / num_of_votes)

perc_of_cand1_votes = '{:.1%}'.format(prop_of_cand1_votes)
perc_of_cand2_votes = '{:.1%}'.format(prop_of_cand2_votes)
perc_of_cand3_votes = '{:.1%}'.format(prop_of_cand3_votes)
perc_of_cand4_votes = '{:.1%}'.format(prop_of_cand4_votes)
        
print("Election Results")
print("-------------------------")
print(str(cand1) + ": " + str(perc_of_cand1_votes) + " " + "(" + str(cand1_count) + ")")
print(str(cand2) + ": " + str(perc_of_cand2_votes) + " " + "(" + str(cand2_count) + ")")
print(str(cand3) + ": " + str(perc_of_cand3_votes) + " " + "(" + str(cand3_count) + ")")
print(str(cand4) + ": " + str(perc_of_cand4_votes) + " " + "(" + str(cand4_count) + ")")
print("-------------------------")
print("Winner: " + election_winner)
print("-------------------------")

Election Results
-------------------------
Vestal: 48.0% (385440)
Torres: 44.0% (353320)
Seth: 5.0% (40150)
Cordin: 3.0% (24090)
-------------------------
Winner: Vestal
-------------------------

In [12]:
vestal_count

385440

In [35]:
import pandas as pd
import csv
import os

election_data = os.path.join("Resources", "election_data_2.csv")
election_data_df = pd.read_csv(election_data, encoding = "ISO-8859-1")
election_data_df_noHead = pd.read_csv(election_data, encoding = "ISO-8859-1",skiprows=1, header=None)

num_of_votes = len(election_data_df_noHead)



candidate_array = election_data_df['Candidate'].unique()
cand1 = candidate_array[0]
cand2 = candidate_array[1]
cand3 = candidate_array[2]
cand4 = candidate_array[3]

cand1_count = 0
cand2_count = 0
cand3_count = 0
cand4_count = 0


with open(election_data, newline="") as csvfile:
    csv_reader = csv.reader(csvfile, delimiter=",")
    
    for row in csv_reader:
        if row[2] == str(cand1):
            cand1_count = cand1_count + 1
        if row[2] == str(cand2):
            cand2_count = cand2_count + 1
        if row[2] == str(cand3):
            cand3_count = cand3_count + 1
        if row[2] == str(cand4):
            cand4_count = cand4_count + 1
            
            
highest_vote_count = 0
election_winner = "No one"

if cand1_count > cand2_count:
    highest_vote_count = cand1_count
    election_winner = str(cand1)
if cand2_count > cand1_count:
    highest_vote_count = cand2_count
    election_winner = str(cand2)
if cand3_count > highest_vote_count:
    highest_vote_count = cand3_count
    election_winner = str(cand3)
if cand4_count > highest_vote_count:
    highest_vote_count = cand4_count
    election_winner = str(cand4)
               
            
prop_of_cand1_votes = (cand1_count / num_of_votes)           
prop_of_cand2_votes = (cand2_count / num_of_votes)
prop_of_cand3_votes = (cand3_count / num_of_votes)
prop_of_cand4_votes = (cand4_count / num_of_votes)

perc_of_cand1_votes = '{:.1%}'.format(prop_of_cand1_votes)
perc_of_cand2_votes = '{:.1%}'.format(prop_of_cand2_votes)
perc_of_cand3_votes = '{:.1%}'.format(prop_of_cand3_votes)
perc_of_cand4_votes = '{:.1%}'.format(prop_of_cand4_votes)
        
print("Election Results")
print("-------------------------")
print(str(cand1) + ": " + str(perc_of_cand1_votes) + " " + "(" + str(cand1_count) + ")")
print(str(cand2) + ": " + str(perc_of_cand2_votes) + " " + "(" + str(cand2_count) + ")")
print(str(cand3) + ": " + str(perc_of_cand3_votes) + " " + "(" + str(cand3_count) + ")")
print(str(cand4) + ": " + str(perc_of_cand4_votes) + " " + "(" + str(cand4_count) + ")")
print("-------------------------")
print("Winner: " + election_winner)
print("-------------------------")

Election Results
-------------------------
Khan: 63.1% (661583)
Correy: 19.9% (209046)
Li: 14.0% (146360)
O'Tooley: 3.0% (31586)
-------------------------
Winner: Khan
-------------------------